services:

  web1:
    build:
      context: ./django/
    command: sh -c "python manage.py collectstatic --no-input && gunicorn demo.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
     - 8000
    env_file:
      - ./.env/dev.env

  web2:
    build:
      context: ./django2/
    command: sh -c "python manage.py collectstatic --no-input && gunicorn demo.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - ./django2/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
     - 8080
    env_file:
      - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
      - ./nginx/v1/:/home/html/v1/
      - ./nginx/v2/:/home/html/v2/

  dns:
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

volumes:
  static_files:

